# Generated by Django 5.2.13 on 2026-04-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
