# Generated by Django 4.2.29 on 2026-04-15 10:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(db_index=True, default='employee', max_length=50)),
                ('status', models.CharField(db_index=True, default='active', max_length=50)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('dtm_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('dtm_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('notified_start', models.BooleanField(default=False)),
                ('notified_overdue', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('dtm_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('dtm_modified', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.app_user')),
            ],
            options={
                'db_table': 'assignment',
                'ordering': ['-dtm_created'],
            },
        ),
        migrations.CreateModel(
            name='forum_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=50)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('dtm_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('dtm_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.app_user')),
            ],
            options={
                'db_table': 'forum',
                'ordering': ['-dtm_created'],
            },
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], db_index=True, default='unread', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.app_user')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='priorityoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'master_priority',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='statusoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'master_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='system_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='task_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('dtm_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('dtm_modified', models.DateTimeField(auto_now=True)),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.priorityoption')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.statusoption')),
            ],
            options={
                'db_table': 'task',
                'ordering': ['-dtm_created'],
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tasksession',
            name='assigned_task',
        ),
        migrations.RemoveField(
            model_name='tasksession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='AssignedTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskSession',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='system_log',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task_management'),
        ),
        migrations.AddField(
            model_name='system_log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.app_user'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.statusoption'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task_management'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['task', 'assigned_to'], name='assignment_task_id_f1dfdb_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assigned_to', 'status'], name='assignment_assigne_56dd72_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['deadline'], name='assignment_deadlin_b87611_idx'),
        ),
    ]
