# Generated by Django 4.2.29 on 2026-04-15 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_app_user_assignment_forum_entry_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('otp', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'otp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='app_user',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='timeline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task_management',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task_management',
            name='lowered_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
