# Generated by Django 4.2.29 on 2026-04-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_otp_entry_app_user_remarks_assignment_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forum_entry',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='forum_entry',
            name='sender_role',
            field=models.CharField(db_index=True, default='user', max_length=20),
        ),
    ]
