# Generated by Django 4.2.29 on 2026-04-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_app_user_profile_image_forum_entry_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='New Notification', max_length=255),
        ),
    ]
