# Generated by Django 4.2.29 on 2026-04-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='New Notification', max_length=255, null=True),
        ),
    ]
