# Generated by Django 4.2.29 on 2026-04-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_notification_created_at_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
