# Generated by Django 4.2.29 on 2026-04-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_app_user_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='roleoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'master_role',
                'ordering': ['name'],
            },
        ),
    ]
