# Generated by Django 4.2.29 on 2026-04-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_roleoption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='roleoption',
        ),
    ]
