# Generated by Django 4.2.29 on 2026-04-21 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_delete_roleoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_entry',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='tasks.app_user'),
        ),
    ]
